<!DOCTYPE html>
<html>
	<head>
		<title>An Error occured</title>

		<!-- Css include -->
		<link href="<?= $this->baseUrlHelper('etc/asset/fewlines/styles/css/application.css') ?>" rel="stylesheet" type="text/css" />
	</head>
	<body class="exception-page">
		<div id="page">
			<?php if( ! $this->getEnvironment() || $this->getEnvironment()->isLocal()): ?>
				<?= $this->renderView() ?>
			<?php else: ?>
				<div class="non-local-error"><?= $this->translate('layout.exception.meta.non-local-error') ?></div>
			<?php endif; ?>
		</div>
	</body>
</html>