<!DOCTYPE html>
<html>
	<head>
		<title>An Error occured</title>
		<!-- Css include -->
		<style><?= file_get_contents($this->resourceHelper('css/application.css')) ?></style>
	</head>
	<body class="exception-page">
		<div id="page">
			<?php if( ! $this->getEnvironment() ||
				($this->getEnvironment() && $this->getEnvironment()->isLocal()) ||
				($this->getEnvironment() && ! $this->getEnvironment()->hasTypes())
			): ?>
				<?= $this->renderView() ?>
			<?php else: ?>
				<div class="non-local-error"><?= $this->translate('layout.exception.meta.non-local-error') ?></div>
			<?php endif; ?>
		</div>
	</body>
</html>