<div class="file-preview">
	<div class="file">
		<span class="path"><?= $file ?></span>
		<table class="lines">
			<?php foreach($this->linePreviewHelper($file, $line, isset($depth) ? $depth : 6) as $lineNum => $linePrev): ?>
				<tr class="line <?= $lineNum == $line ? 'highlight' : '' ?>">
					<td class="num"><?= $lineNum ?>:</td>
					<td class="content"><pre><?= $linePrev ?></pre></td>
				</tr>
			<?php endforeach; ?>
		</table>
	</div>
</div>